const mongoose = require("mongoose");
const dotenv = require("dotenv");

dotenv.config({ path: "./config/config.env" });

const Provider = require("./models/Provider");
const Car = require("./models/Car");

// Generate car image URL from brand, model, color using imagin.studio CDN (free, no API key needed)
function carImageUrl(brand, model, color) {
  const make = encodeURIComponent(brand.toLowerCase());
  const family = encodeURIComponent(model.split(" ")[0].toLowerCase());
  const paint = encodeURIComponent(color.toLowerCase());
  return `https://cdn.imagin.studio/getimage?customer=img&make=${make}&modelFamily=${family}&paintDescription=${paint}&angle=29&zoomType=fullscreen&width=800`;
}

const providers = [
  {
    name: "Bangkok Premium Cars",
    address: "123 Sukhumvit Rd, Khlong Toei, Bangkok 10110",
    telephone: "02-123-4567",
  },
  {
    name: "Siam Auto Rental",
    address: "456 Rama IV Rd, Pathum Wan, Bangkok 10330",
    telephone: "02-234-5678",
  },
  {
    name: "Thai Drive Hub",
    address: "789 Silom Rd, Bang Rak, Bangkok 10500",
    telephone: "02-345-6789",
  },
  {
    name: "Capital City Motors",
    address: "55 Ratchadaphisek Rd, Din Daeng, Bangkok 10400",
    telephone: "02-456-7890",
  },
  {
    name: "BKK Express Wheels",
    address: "12 Lat Phrao Rd, Chatuchak, Bangkok 10900",
    telephone: "02-567-8901",
  },
  {
    name: "Royal Garage Bangkok",
    address: "88 Phetchaburi Rd, Ratchathewi, Bangkok 10400",
    telephone: "02-678-9012",
  },
  {
    name: "Asoke Car Rental",
    address: "33 Asoke Montri Rd, Watthana, Bangkok 10110",
    telephone: "02-789-0123",
  },
  {
    name: "Chiang Mai Wheels",
    address: "321 Nimmanhaemin Rd, Su Thep, Chiang Mai 50200",
    telephone: "053-456-789",
  },
  {
    name: "Lanna Ride",
    address: "19 Huay Kaew Rd, Mueang, Chiang Mai 50300",
    telephone: "053-567-890",
  },
  {
    name: "Northern Star Auto",
    address: "240 Chang Klan Rd, Mueang, Chiang Mai 50100",
    telephone: "053-678-901",
  },
  {
    name: "Phuket Island Cars",
    address: "99 Thalang Rd, Mueang Phuket, Phuket 83000",
    telephone: "076-567-890",
  },
  {
    name: "Andaman Auto",
    address: "45 Phang Nga Rd, Mueang Phuket, Phuket 83000",
    telephone: "076-678-901",
  },
  {
    name: "Patong Beach Rental",
    address: "78 Bangla Rd, Pa Tong, Phuket 83150",
    telephone: "076-789-012",
  },
  {
    name: "Pattaya Speed Rent",
    address: "222 Beach Rd, Bang Lamung, Pattaya 20150",
    telephone: "038-123-456",
  },
  {
    name: "East Coast Motors",
    address: "150 Sukhumvit Rd, Pattaya, Chon Buri 20260",
    telephone: "038-234-567",
  },
  {
    name: "Hua Hin Cruiser",
    address: "56 Phetkasem Rd, Hua Hin, Prachuap 77110",
    telephone: "032-345-678",
  },
  {
    name: "Isan Auto Rental",
    address: "88 Sri Chan Rd, Mueang, Khon Kaen 40000",
    telephone: "043-456-789",
  },
  {
    name: "Southern Wheels",
    address: "123 Niphat Uthit 3 Rd, Hat Yai, Songkhla 90110",
    telephone: "074-567-890",
  },
  {
    name: "Krabi Adventure Cars",
    address: "9 Maharaj Rd, Mueang Krabi, Krabi 81000",
    telephone: "075-678-901",
  },
  {
    name: "Samui Island Drive",
    address: "44 Chaweng Beach Rd, Ko Samui, Surat Thani 84320",
    telephone: "077-789-012",
  },
];

const C = [
  // 0: Bangkok Premium Cars (8)
  {
    brand: "Toyota",
    model: "Camry",
    color: "White",
    licensePlate: "กข 1234",
    dailyRate: 1800,
    available: true,
    p: 0,
  },
  {
    brand: "Honda",
    model: "Accord",
    color: "Black",
    licensePlate: "กค 5678",
    dailyRate: 1900,
    available: true,
    p: 0,
  },
  {
    brand: "BMW",
    model: "3 Series",
    color: "Blue",
    licensePlate: "ขข 9012",
    dailyRate: 3500,
    available: true,
    p: 0,
  },
  {
    brand: "Mercedes-Benz",
    model: "C-Class",
    color: "Silver",
    licensePlate: "ขค 3456",
    dailyRate: 4000,
    available: true,
    p: 0,
  },
  {
    brand: "Toyota",
    model: "Fortuner",
    color: "Gray",
    licensePlate: "คก 7890",
    dailyRate: 2500,
    available: false,
    p: 0,
  },
  {
    brand: "Lexus",
    model: "ES",
    color: "Black",
    licensePlate: "คข 1357",
    dailyRate: 5500,
    available: true,
    p: 0,
  },
  {
    brand: "Audi",
    model: "A4",
    color: "White",
    licensePlate: "คค 2468",
    dailyRate: 4200,
    available: true,
    p: 0,
  },
  {
    brand: "Volvo",
    model: "S60",
    color: "Gray",
    licensePlate: "คง 3579",
    dailyRate: 3800,
    available: false,
    p: 0,
  },

  // 1: Siam Auto Rental (10)
  {
    brand: "Toyota",
    model: "Yaris",
    color: "Red",
    licensePlate: "งง 1111",
    dailyRate: 900,
    available: true,
    p: 1,
  },
  {
    brand: "Honda",
    model: "City",
    color: "White",
    licensePlate: "งจ 2222",
    dailyRate: 1000,
    available: true,
    p: 1,
  },
  {
    brand: "Nissan",
    model: "Almera",
    color: "Silver",
    licensePlate: "จก 3333",
    dailyRate: 850,
    available: true,
    p: 1,
  },
  {
    brand: "Mazda",
    model: "2",
    color: "Red",
    licensePlate: "จข 4444",
    dailyRate: 950,
    available: false,
    p: 1,
  },
  {
    brand: "Suzuki",
    model: "Swift",
    color: "Orange",
    licensePlate: "จค 5555",
    dailyRate: 800,
    available: true,
    p: 1,
  },
  {
    brand: "MG",
    model: "5",
    color: "Black",
    licensePlate: "จง 6666",
    dailyRate: 1100,
    available: true,
    p: 1,
  },
  {
    brand: "Toyota",
    model: "Vios",
    color: "Gray",
    licensePlate: "จจ 7777",
    dailyRate: 850,
    available: true,
    p: 1,
  },
  {
    brand: "Honda",
    model: "Brio",
    color: "Yellow",
    licensePlate: "จฉ 8888",
    dailyRate: 750,
    available: true,
    p: 1,
  },
  {
    brand: "Nissan",
    model: "March",
    color: "Green",
    licensePlate: "จช 9999",
    dailyRate: 700,
    available: true,
    p: 1,
  },
  {
    brand: "Mitsubishi",
    model: "Attrage",
    color: "White",
    licensePlate: "จซ 1010",
    dailyRate: 800,
    available: false,
    p: 1,
  },

  // 2: Thai Drive Hub (7)
  {
    brand: "Toyota",
    model: "Corolla Cross",
    color: "White",
    licensePlate: "ฉก 7777",
    dailyRate: 1600,
    available: true,
    p: 2,
  },
  {
    brand: "Honda",
    model: "HR-V",
    color: "Gray",
    licensePlate: "ฉข 8888",
    dailyRate: 1700,
    available: true,
    p: 2,
  },
  {
    brand: "Mazda",
    model: "CX-5",
    color: "Red",
    licensePlate: "ฉค 9999",
    dailyRate: 2200,
    available: true,
    p: 2,
  },
  {
    brand: "Isuzu",
    model: "MU-X",
    color: "Blue",
    licensePlate: "ชก 1010",
    dailyRate: 2000,
    available: false,
    p: 2,
  },
  {
    brand: "Ford",
    model: "Everest",
    color: "Black",
    licensePlate: "ชข 2020",
    dailyRate: 2800,
    available: true,
    p: 2,
  },
  {
    brand: "Toyota",
    model: "Land Cruiser",
    color: "White",
    licensePlate: "ชค 3030",
    dailyRate: 6500,
    available: true,
    p: 2,
  },
  {
    brand: "Mitsubishi",
    model: "Pajero",
    color: "Silver",
    licensePlate: "ชง 4040",
    dailyRate: 2400,
    available: true,
    p: 2,
  },

  // 3: Capital City Motors — EV (8)
  {
    brand: "Tesla",
    model: "Model 3",
    color: "White",
    licensePlate: "ซซ 1001",
    dailyRate: 4500,
    available: true,
    p: 3,
  },
  {
    brand: "Tesla",
    model: "Model Y",
    color: "Black",
    licensePlate: "ซซ 1002",
    dailyRate: 5000,
    available: true,
    p: 3,
  },
  {
    brand: "BYD",
    model: "Atto 3",
    color: "Blue",
    licensePlate: "ซซ 1003",
    dailyRate: 2200,
    available: true,
    p: 3,
  },
  {
    brand: "BYD",
    model: "Dolphin",
    color: "Pink",
    licensePlate: "ซซ 1004",
    dailyRate: 1500,
    available: true,
    p: 3,
  },
  {
    brand: "MG",
    model: "ZS",
    color: "Green",
    licensePlate: "ซซ 1005",
    dailyRate: 1800,
    available: false,
    p: 3,
  },
  {
    brand: "Neta",
    model: "V",
    color: "White",
    licensePlate: "ซซ 1006",
    dailyRate: 1200,
    available: true,
    p: 3,
  },
  {
    brand: "ORA",
    model: "Good Cat",
    color: "Pink",
    licensePlate: "ซซ 1007",
    dailyRate: 1600,
    available: true,
    p: 3,
  },
  {
    brand: "Volvo",
    model: "XC40",
    color: "Gray",
    licensePlate: "ซซ 1008",
    dailyRate: 4800,
    available: true,
    p: 3,
  },

  // 4: BKK Express Wheels (6)
  {
    brand: "Toyota",
    model: "Hilux",
    color: "White",
    licensePlate: "ฎก 2001",
    dailyRate: 1400,
    available: true,
    p: 4,
  },
  {
    brand: "Isuzu",
    model: "D-Max",
    color: "Blue",
    licensePlate: "ฎข 2002",
    dailyRate: 1300,
    available: true,
    p: 4,
  },
  {
    brand: "Ford",
    model: "Ranger",
    color: "Orange",
    licensePlate: "ฎค 2003",
    dailyRate: 1500,
    available: true,
    p: 4,
  },
  {
    brand: "Nissan",
    model: "Navara",
    color: "Black",
    licensePlate: "ฎง 2004",
    dailyRate: 1350,
    available: false,
    p: 4,
  },
  {
    brand: "Toyota",
    model: "Commuter",
    color: "White",
    licensePlate: "ฎจ 2005",
    dailyRate: 2500,
    available: true,
    p: 4,
  },
  {
    brand: "Toyota",
    model: "Alphard",
    color: "Black",
    licensePlate: "ฎฉ 2006",
    dailyRate: 5000,
    available: true,
    p: 4,
  },

  // 5: Royal Garage (5)
  {
    brand: "Porsche",
    model: "Cayenne",
    color: "Black",
    licensePlate: "ฏก 3001",
    dailyRate: 9000,
    available: true,
    p: 5,
  },
  {
    brand: "BMW",
    model: "X5",
    color: "White",
    licensePlate: "ฏข 3002",
    dailyRate: 7500,
    available: true,
    p: 5,
  },
  {
    brand: "Mercedes-Benz",
    model: "GLE",
    color: "Silver",
    licensePlate: "ฏค 3003",
    dailyRate: 8000,
    available: true,
    p: 5,
  },
  {
    brand: "Land Rover",
    model: "Range Rover Sport",
    color: "Green",
    licensePlate: "ฏง 3004",
    dailyRate: 12000,
    available: false,
    p: 5,
  },
  {
    brand: "Bentley",
    model: "Bentayga",
    color: "Black",
    licensePlate: "ฏจ 3005",
    dailyRate: 25000,
    available: true,
    p: 5,
  },

  // 6: Asoke Car Rental (6)
  {
    brand: "Honda",
    model: "Civic",
    color: "White",
    licensePlate: "ฐก 4001",
    dailyRate: 1500,
    available: true,
    p: 6,
  },
  {
    brand: "Toyota",
    model: "Corolla",
    color: "Silver",
    licensePlate: "ฐข 4002",
    dailyRate: 1400,
    available: true,
    p: 6,
  },
  {
    brand: "Mazda",
    model: "3",
    color: "Red",
    licensePlate: "ฐค 4003",
    dailyRate: 1600,
    available: true,
    p: 6,
  },
  {
    brand: "Hyundai",
    model: "Elantra",
    color: "Blue",
    licensePlate: "ฐง 4004",
    dailyRate: 1300,
    available: true,
    p: 6,
  },
  {
    brand: "Kia",
    model: "Cerato",
    color: "Gray",
    licensePlate: "ฐจ 4005",
    dailyRate: 1250,
    available: false,
    p: 6,
  },
  {
    brand: "MG",
    model: "EP",
    color: "White",
    licensePlate: "ฐฉ 4006",
    dailyRate: 1400,
    available: true,
    p: 6,
  },

  // 7: Chiang Mai Wheels (6)
  {
    brand: "Toyota",
    model: "Vios",
    color: "White",
    licensePlate: "ซก 3030",
    dailyRate: 800,
    available: true,
    p: 7,
  },
  {
    brand: "Honda",
    model: "Jazz",
    color: "Yellow",
    licensePlate: "ซข 4040",
    dailyRate: 900,
    available: true,
    p: 7,
  },
  {
    brand: "Nissan",
    model: "Note",
    color: "Green",
    licensePlate: "ซค 5050",
    dailyRate: 850,
    available: true,
    p: 7,
  },
  {
    brand: "Toyota",
    model: "Hilux",
    color: "Black",
    licensePlate: "ฌก 6060",
    dailyRate: 1500,
    available: true,
    p: 7,
  },
  {
    brand: "Suzuki",
    model: "Celerio",
    color: "Silver",
    licensePlate: "ฌข 6161",
    dailyRate: 650,
    available: true,
    p: 7,
  },
  {
    brand: "Mazda",
    model: "CX-30",
    color: "Red",
    licensePlate: "ฌค 6262",
    dailyRate: 1800,
    available: false,
    p: 7,
  },

  // 8: Lanna Ride (5)
  {
    brand: "Suzuki",
    model: "Jimny",
    color: "Green",
    licensePlate: "ญญ 5001",
    dailyRate: 2000,
    available: true,
    p: 8,
  },
  {
    brand: "Toyota",
    model: "Fortuner",
    color: "White",
    licensePlate: "ญญ 5002",
    dailyRate: 2500,
    available: true,
    p: 8,
  },
  {
    brand: "Ford",
    model: "Ranger Raptor",
    color: "Blue",
    licensePlate: "ญญ 5003",
    dailyRate: 3500,
    available: true,
    p: 8,
  },
  {
    brand: "Mitsubishi",
    model: "Triton",
    color: "Orange",
    licensePlate: "ญญ 5004",
    dailyRate: 1600,
    available: true,
    p: 8,
  },
  {
    brand: "Isuzu",
    model: "D-Max",
    color: "Gray",
    licensePlate: "ญญ 5005",
    dailyRate: 1800,
    available: false,
    p: 8,
  },

  // 9: Northern Star Auto (5)
  {
    brand: "Honda",
    model: "CR-V",
    color: "White",
    licensePlate: "ฎฎ 6001",
    dailyRate: 2200,
    available: true,
    p: 9,
  },
  {
    brand: "Toyota",
    model: "Yaris",
    color: "Blue",
    licensePlate: "ฎฎ 6002",
    dailyRate: 850,
    available: true,
    p: 9,
  },
  {
    brand: "Nissan",
    model: "Kicks",
    color: "Red",
    licensePlate: "ฎฎ 6003",
    dailyRate: 1500,
    available: true,
    p: 9,
  },
  {
    brand: "MG",
    model: "HS",
    color: "Black",
    licensePlate: "ฎฎ 6004",
    dailyRate: 1700,
    available: true,
    p: 9,
  },
  {
    brand: "Honda",
    model: "WR-V",
    color: "Silver",
    licensePlate: "ฎฎ 6005",
    dailyRate: 1400,
    available: false,
    p: 9,
  },

  // 10: Phuket Island Cars (7)
  {
    brand: "BMW",
    model: "Z4",
    color: "Red",
    licensePlate: "ญก 7070",
    dailyRate: 5500,
    available: true,
    p: 10,
  },
  {
    brand: "Mazda",
    model: "MX-5",
    color: "Blue",
    licensePlate: "ญข 8080",
    dailyRate: 4500,
    available: true,
    p: 10,
  },
  {
    brand: "Mini",
    model: "Cooper",
    color: "Green",
    licensePlate: "ญค 9090",
    dailyRate: 3800,
    available: true,
    p: 10,
  },
  {
    brand: "Toyota",
    model: "Fortuner",
    color: "White",
    licensePlate: "ภก 1212",
    dailyRate: 2500,
    available: true,
    p: 10,
  },
  {
    brand: "Jeep",
    model: "Wrangler",
    color: "Orange",
    licensePlate: "ภข 3434",
    dailyRate: 6000,
    available: false,
    p: 10,
  },
  {
    brand: "Porsche",
    model: "718 Boxster",
    color: "Yellow",
    licensePlate: "ภค 5656",
    dailyRate: 9500,
    available: true,
    p: 10,
  },
  {
    brand: "Mercedes-Benz",
    model: "SLC",
    color: "White",
    licensePlate: "ภง 7878",
    dailyRate: 7000,
    available: true,
    p: 10,
  },

  // 11: Andaman Auto (5)
  {
    brand: "Toyota",
    model: "Innova",
    color: "Silver",
    licensePlate: "ณก 7001",
    dailyRate: 1800,
    available: true,
    p: 11,
  },
  {
    brand: "Honda",
    model: "BR-V",
    color: "White",
    licensePlate: "ณข 7002",
    dailyRate: 1600,
    available: true,
    p: 11,
  },
  {
    brand: "Suzuki",
    model: "Ertiga",
    color: "Gray",
    licensePlate: "ณค 7003",
    dailyRate: 1400,
    available: true,
    p: 11,
  },
  {
    brand: "Mitsubishi",
    model: "Xpander",
    color: "Black",
    licensePlate: "ณง 7004",
    dailyRate: 1500,
    available: false,
    p: 11,
  },
  {
    brand: "Toyota",
    model: "Veloz",
    color: "Red",
    licensePlate: "ณจ 7005",
    dailyRate: 1550,
    available: true,
    p: 11,
  },

  // 12: Patong Beach Rental (5)
  {
    brand: "Mini",
    model: "Countryman",
    color: "Blue",
    licensePlate: "ดก 8001",
    dailyRate: 3200,
    available: true,
    p: 12,
  },
  {
    brand: "Fiat",
    model: "500",
    color: "Red",
    licensePlate: "ดข 8002",
    dailyRate: 2500,
    available: true,
    p: 12,
  },
  {
    brand: "Volkswagen",
    model: "Beetle",
    color: "Yellow",
    licensePlate: "ดค 8003",
    dailyRate: 2800,
    available: true,
    p: 12,
  },
  {
    brand: "Suzuki",
    model: "Jimny",
    color: "Green",
    licensePlate: "ดง 8004",
    dailyRate: 2200,
    available: true,
    p: 12,
  },
  {
    brand: "Jeep",
    model: "Compass",
    color: "White",
    licensePlate: "ดจ 8005",
    dailyRate: 3500,
    available: false,
    p: 12,
  },

  // 13: Pattaya Speed Rent (7)
  {
    brand: "Honda",
    model: "Civic Type R",
    color: "White",
    licensePlate: "ตก 9001",
    dailyRate: 4500,
    available: true,
    p: 13,
  },
  {
    brand: "Toyota",
    model: "Supra",
    color: "Red",
    licensePlate: "ตข 9002",
    dailyRate: 6500,
    available: true,
    p: 13,
  },
  {
    brand: "Mazda",
    model: "MX-5",
    color: "Gray",
    licensePlate: "ตค 9003",
    dailyRate: 4800,
    available: true,
    p: 13,
  },
  {
    brand: "Nissan",
    model: "370Z",
    color: "Blue",
    licensePlate: "ตง 9004",
    dailyRate: 5500,
    available: false,
    p: 13,
  },
  {
    brand: "Ford",
    model: "Mustang",
    color: "Yellow",
    licensePlate: "ตจ 9005",
    dailyRate: 7000,
    available: true,
    p: 13,
  },
  {
    brand: "Chevrolet",
    model: "Camaro",
    color: "Black",
    licensePlate: "ตฉ 9006",
    dailyRate: 7500,
    available: true,
    p: 13,
  },
  {
    brand: "BMW",
    model: "M4",
    color: "Orange",
    licensePlate: "ตช 9007",
    dailyRate: 8500,
    available: true,
    p: 13,
  },

  // 14: East Coast Motors (5)
  {
    brand: "Toyota",
    model: "Yaris",
    color: "White",
    licensePlate: "ถก 1101",
    dailyRate: 850,
    available: true,
    p: 14,
  },
  {
    brand: "Honda",
    model: "City",
    color: "Red",
    licensePlate: "ถข 1102",
    dailyRate: 1050,
    available: true,
    p: 14,
  },
  {
    brand: "Nissan",
    model: "Almera",
    color: "Silver",
    licensePlate: "ถค 1103",
    dailyRate: 800,
    available: true,
    p: 14,
  },
  {
    brand: "Toyota",
    model: "Corolla Cross",
    color: "Black",
    licensePlate: "ถง 1104",
    dailyRate: 1700,
    available: true,
    p: 14,
  },
  {
    brand: "MG",
    model: "VS",
    color: "Blue",
    licensePlate: "ถจ 1105",
    dailyRate: 1300,
    available: false,
    p: 14,
  },

  // 15: Hua Hin Cruiser (6)
  {
    brand: "BMW",
    model: "4 Series",
    color: "White",
    licensePlate: "ทก 1201",
    dailyRate: 6000,
    available: true,
    p: 15,
  },
  {
    brand: "Mercedes-Benz",
    model: "E-Class",
    color: "Silver",
    licensePlate: "ทข 1202",
    dailyRate: 6500,
    available: true,
    p: 15,
  },
  {
    brand: "Toyota",
    model: "Camry",
    color: "Black",
    licensePlate: "ทค 1203",
    dailyRate: 1800,
    available: true,
    p: 15,
  },
  {
    brand: "Honda",
    model: "Accord",
    color: "White",
    licensePlate: "ทง 1204",
    dailyRate: 1900,
    available: true,
    p: 15,
  },
  {
    brand: "Mazda",
    model: "CX-5",
    color: "Red",
    licensePlate: "ทจ 1205",
    dailyRate: 2200,
    available: false,
    p: 15,
  },
  {
    brand: "Hyundai",
    model: "Ioniq 5",
    color: "Gray",
    licensePlate: "ทฉ 1206",
    dailyRate: 3500,
    available: true,
    p: 15,
  },

  // 16: Isan Auto Rental (6)
  {
    brand: "Toyota",
    model: "Vios",
    color: "White",
    licensePlate: "ธก 1301",
    dailyRate: 750,
    available: true,
    p: 16,
  },
  {
    brand: "Nissan",
    model: "Almera",
    color: "Silver",
    licensePlate: "ธข 1302",
    dailyRate: 700,
    available: true,
    p: 16,
  },
  {
    brand: "Suzuki",
    model: "Celerio",
    color: "Blue",
    licensePlate: "ธค 1303",
    dailyRate: 600,
    available: true,
    p: 16,
  },
  {
    brand: "Honda",
    model: "Brio",
    color: "Red",
    licensePlate: "ธง 1304",
    dailyRate: 650,
    available: true,
    p: 16,
  },
  {
    brand: "Isuzu",
    model: "D-Max",
    color: "Black",
    licensePlate: "ธจ 1305",
    dailyRate: 1200,
    available: true,
    p: 16,
  },
  {
    brand: "Toyota",
    model: "Hilux",
    color: "White",
    licensePlate: "ธฉ 1306",
    dailyRate: 1300,
    available: false,
    p: 16,
  },

  // 17: Southern Wheels (5)
  {
    brand: "Toyota",
    model: "Yaris",
    color: "White",
    licensePlate: "นก 1401",
    dailyRate: 800,
    available: true,
    p: 17,
  },
  {
    brand: "Honda",
    model: "City",
    color: "Gray",
    licensePlate: "นข 1402",
    dailyRate: 950,
    available: true,
    p: 17,
  },
  {
    brand: "Toyota",
    model: "Fortuner",
    color: "Black",
    licensePlate: "นค 1403",
    dailyRate: 2500,
    available: true,
    p: 17,
  },
  {
    brand: "Isuzu",
    model: "MU-X",
    color: "Silver",
    licensePlate: "นง 1404",
    dailyRate: 2200,
    available: false,
    p: 17,
  },
  {
    brand: "Mazda",
    model: "2",
    color: "Red",
    licensePlate: "นจ 1405",
    dailyRate: 900,
    available: true,
    p: 17,
  },

  // 18: Krabi Adventure Cars (6)
  {
    brand: "Suzuki",
    model: "Jimny",
    color: "Green",
    licensePlate: "บก 1501",
    dailyRate: 2200,
    available: true,
    p: 18,
  },
  {
    brand: "Jeep",
    model: "Wrangler",
    color: "Black",
    licensePlate: "บข 1502",
    dailyRate: 5500,
    available: true,
    p: 18,
  },
  {
    brand: "Toyota",
    model: "Hilux",
    color: "Orange",
    licensePlate: "บค 1503",
    dailyRate: 2000,
    available: true,
    p: 18,
  },
  {
    brand: "Ford",
    model: "Ranger",
    color: "Blue",
    licensePlate: "บง 1504",
    dailyRate: 2200,
    available: true,
    p: 18,
  },
  {
    brand: "Mitsubishi",
    model: "Triton",
    color: "White",
    licensePlate: "บจ 1505",
    dailyRate: 1800,
    available: false,
    p: 18,
  },
  {
    brand: "Land Rover",
    model: "Defender",
    color: "Green",
    licensePlate: "บฉ 1506",
    dailyRate: 8000,
    available: true,
    p: 18,
  },

  // 19: Samui Island Drive (5)
  {
    brand: "Mini",
    model: "Cooper",
    color: "Red",
    licensePlate: "ปก 1601",
    dailyRate: 3000,
    available: true,
    p: 19,
  },
  {
    brand: "Suzuki",
    model: "Swift",
    color: "Blue",
    licensePlate: "ปข 1602",
    dailyRate: 900,
    available: true,
    p: 19,
  },
  {
    brand: "Toyota",
    model: "Yaris",
    color: "White",
    licensePlate: "ปค 1603",
    dailyRate: 850,
    available: true,
    p: 19,
  },
  {
    brand: "Honda",
    model: "Jazz",
    color: "Orange",
    licensePlate: "ปง 1604",
    dailyRate: 950,
    available: false,
    p: 19,
  },
  {
    brand: "Mazda",
    model: "CX-3",
    color: "Red",
    licensePlate: "ปจ 1605",
    dailyRate: 1800,
    available: true,
    p: 19,
  },
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("Connected to MongoDB\n");
    const dc = await Car.deleteMany({});
    const dp = await Provider.deleteMany({});
    console.log(
      `Cleared ${dp.deletedCount} providers, ${dc.deletedCount} cars\n`,
    );
    const created = await Provider.insertMany(providers);
    console.log(`Created ${created.length} providers`);

    const cars = C.map((c) => ({
      brand: c.brand,
      model: c.model,
      color: c.color,
      licensePlate: c.licensePlate,
      dailyRate: c.dailyRate,
      available: c.available,
      image: carImageUrl(c.brand, c.model, c.color),
      provider: created[c.p]._id,
    }));

    const cc = await Car.insertMany(cars);
    console.log(`Created ${cc.length} cars (with auto-generated images)\n`);

    console.log("─".repeat(60));
    for (let i = 0; i < created.length; i++) {
      const all = C.filter((c) => c.p === i);
      const av = all.filter((c) => c.available).length;
      console.log(
        `  ${String(i + 1).padStart(2)}) ${created[i].name.padEnd(26)} ${String(all.length).padStart(2)} cars (${av} avail)`,
      );
    }
    console.log("─".repeat(60));
    console.log(`  Total: ${created.length} providers, ${cc.length} cars`);
    console.log("\n  Image URLs generated from: cdn.imagin.studio");
    console.log("  (brand + model + color = exact car image)\n");
    console.log("Done!");
    process.exit(0);
  } catch (err) {
    console.error("Error:", err.message);
    process.exit(1);
  }
}
seed();
